### ISSUE TITLE
Error in "Open a previous study from a fjm file"

### ISSUE THREAD

**Issue by gargee18** [Rocsg/Fijiyama#3] opened 2023-10-24 12:51 UTC
Cannot open a previous study with an fjm file. 

The log window describes the issue as "Wrong transform file or file selection was incompletely done in interface.
Please select a *.transform.tif file or a *.txt file". 

Same error while selecting a  *.transform.tif file or a *.txt file.

![Screenshot_2023-10-24_14-50-42](https://github.com/Rocsg/Fijiyama/assets/71042852/07752360-be8e-480b-b64f-8038b6aab7be)

**Comment by Rocsg** [comment] 2023-10-25 08:42
Hi, Gargee. Can you please provide me a way to reproduce the bug (the sequence of actions to run in order to produce it). Can it be reproduced with the Fijiyama official test data ?

Thank you in advance,

Romain

**Comment by gargee18** [comment] 2023-10-25 09:04
Yes, it can be reproduced with the Fijiyama official test data.

I reproduced the experiments (Two images registration and series registration) and saved the exported data and registration files in output folders. Next I tried to do "open a previous study": Fiji->Plugins->Fijiyama->Open a previous study->Output folder->Fijiyama_series-...-47.fjm and then I came across the previously mentioned bug.

**Comment by Rocsg** [comment] 2023-10-25 09:18
Hello Gargee,
I am trying to reproduce. To be sure, can you open the .fjm file, and put it into this discussion ? The content should be a small text file

**Comment by gargee18** [comment] 2023-10-25 09:27
#Fijiyama save###
#Name=Fijiyama_series_2023-10-23_04-47
#Mode=Series
#Output path=/home/phukon/Downloads/test_series
#Input path=/home/phukon/Downloads/Fijiyama_DOI/Case_04_Time_series/Input_data/
#Reference Time=0
#Reference Modality=0
#Step=14
#NbSteps=17
#
#Nmods=1
#Mod0=
#
#Ntimes=4
#Time0=0
#Time1=1
#Time2=2
#Time3=3
#
#Expression=MRI_D{Time}.tif
#PathToMask=None
#
#< Done   > Step 0   Manual reg.Transform=RIGID Mov=t1_mod0 -> Ref=t0_mod0   in 3d-viewer
#< Done   > Step 1   Manual reg.Transform=RIGID Mov=t2_mod0 -> Ref=t1_mod0   in 3d-viewer
#< Done   > Step 2   Manual reg.Transform=RIGID Mov=t3_mod0 -> Ref=t2_mod0   in 3d-viewer
#< Done   > Step 3   Save actions and results  
#< Done   > Step 4   Export results  
#< Done   > Step 5   Auto. reg.  Transform=RIGID Mov=t1_mod0 -> Ref=t0_mod0    BM levs=3->-1 it=10 bh=7 nei=2 strd=9DispAll
#< Done   > Step 6   Auto. reg.  Transform=RIGID Mov=t2_mod0 -> Ref=t1_mod0    BM levs=3->-1 it=10 bh=7 nei=2 strd=9DispAll
#< Done   > Step 7   Auto. reg.  Transform=RIGID Mov=t3_mod0 -> Ref=t2_mod0    BM levs=3->-1 it=10 bh=7 nei=2 strd=9DispAll
#< Done   > Step 8   Save actions and results  
#< Done   > Step 9   Export results  
#< Done   > Step 10   Auto. reg.  Transform=DENSE Mov=t1_mod0 -> Ref=t0_mod0    BM levs=2->-1 sigma=0.796875012451172 it=5 bh=7 nei=2 strd=9DispAll
#< Done   > Step 11   Auto. reg.  Transform=DENSE Mov=t2_mod0 -> Ref=t1_mod0    BM levs=2->-1 sigma=0.796875012451172 it=5 bh=7 nei=2 strd=9DispAll
#< Done   > Step 12   Auto. reg.  Transform=DENSE Mov=t3_mod0 -> Ref=t2_mod0    BM levs=2->-1 sigma=0.796875012451172 it=5 bh=7 nei=2 strd=9DispAll
#< Done   > Step 13   Save actions and results  
#< To do > Step 14   Export results  
#< To do > Step 15   Align. axis  Transform=RIGID Mov=t0_mod0 -> Ref=t0_mod0   in 3d-viewer
#< To do > Step 16   Export results  
#

**Comment by Rocsg** [comment] 2023-10-25 10:07
There seems to be an issue with the last published version of the external library ITK, with the writeTransform function. For some reason, the written file contains uneven characters (open the transform.txt file, you will find out. The bug is unnoticeable with files written earlier (weeks ago). 

I am preparing a quickfix to circumvent this point, however the best should be to raise the issue to ITK guys. It is a bit hard to work from where I am currently, but I keep you in touch in the next hour when pushing the quickfix.

**Comment by Rocsg** [comment] 2023-10-25 10:42
I pushed the quickfix on the official integrated distribution (within Fiji). Make Help>Update to get it (version patch index is "Gargee fix"). Can you come back to inform about the fixing status ? That way I'll close the issue

See you
Romain

**Comment by gargee18** [comment] 2023-10-25 11:22
It works! Thank you.

**Closed** 2023-10-25 11:26 UTC
